apiVersion: v1
kind: PersistentVolume
metadata:
  name: brigadasos-komga-shared-pv
  labels:
    type: local
    app: brigadasos-komga
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/brigadasos-shared"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brigadasos-komga-shared-pv-claim
  labels:
    app: brigadasos-komga
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brigadasos-komga-config-pv-claim
  labels:
    app: brigadasos-komga
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brigadasos-komga
  namespace: brigadasos-komga
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: brigadasos-komga
  template:
    metadata:
      labels:
        app: brigadasos-komga
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: brigadasos-komga
          name: brigadasos-komga
          ports:
            - containerPort: 25600
          volumeMounts:
          - mountPath: /config
            name: brigadasos-komga-config-vol
          - mountPath: /shared
            name: brigadasos-komga-shared-vol
      volumes:
        - name: brigadasos-komga-config-vol
          persistentVolumeClaim:
            claimName: brigadasos-komga-config-pv-claim
        - name: brigadasos-komga-shared-vol
          persistentVolumeClaim:
            claimName: brigadasos-komga-shared-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: brigadasos-komga-service
  namespace: brigadasos-komga
  labels:
    app: brigadasos-komga
spec:
  selector:
    app: brigadasos-komga
  ports:
   - port: 25600
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: brigadasos-komga-cert
  namespace: brigadasos-komga
spec:
  secretName: certificate-brigadasos-komga
  dnsNames:
    - biblioteca.brigadasos.xyz
  issuerRef:
    name: clusterissuer-le
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brigadasos-komga-ingress
  namespace: brigadasos-komga
  labels:
    app: brigadasos-komga
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: clusterissuer-le
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - biblioteca.brigadasos.xyz
      secretName: certificate-brigadasos-komga
  rules:
    - host: biblioteca.brigadasos.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: brigadasos-komga-service
                port:
                  number: 25600