apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- brigadasos-komga.yaml
namespace: brigadasos-komga
images:
- name: brigadasos-komga
  newName: ghcr.io/brigadasos/komga
  newTag: "0.0.3"
